## Docking results analysis

In [3]:
docking_df = pd.DataFrame(columns=['name', 'mode', 'affinity_kcal_mol', 'dist_lb', 'dist_ub'])
path = "./"
with open(path + "all_results.txt", "r") as f:
    for line in f:
        data_dict = {}
        if line[0:6] == 'Ligand':
            try:
                found = re.search('ligands\/(.*)\.pdbqt', line).group(1)
            except AttributeError:
                # not found in the original string
                found = 'no_name'
        if line.count('+') == 3:
            try:
                while 'Vina' not in line:
                    line = next(f)
                    if "Vina" not in line:
                        line_ls = [el for el in line.split(' ') if el != '']
                        data_dict['mode'] = line_ls[0]
                        data_dict['affinity_kcal_mol'] = line_ls[1]
                        data_dict['dist_lb'] = line_ls[2]
                        data_dict['dist_ub'] = line_ls[3]
                        data_dict['name'] = found
                        docking_df = docking_df.append(data_dict, ignore_index=True)
            except:
                continue

In [4]:
docking_df['dist_ub'] = docking_df['dist_ub'].str.replace('\n', '')

In [5]:
for col in ['mode', 'affinity_kcal_mol', 'dist_lb', 'dist_ub']:
    docking_df[col] = docking_df[col].astype(float)

In [12]:
docking_df.sort_values(['affinity_kcal_mol']).head(15)

              name  mode  affinity_kcal_mol  dist_lb  dist_ub
6268   gen_mol1631   1.0             -7.702    0.000    0.000
13737   gen_mol782   1.0             -7.561    0.000    0.000
6269   gen_mol1631   2.0             -7.527    1.672    2.522
6886   gen_mol1694   1.0             -7.483    0.000    0.000
6887   gen_mol1694   2.0             -7.468    1.023    1.271
2351   gen_mol1237   2.0             -7.451    3.622    8.229
2350   gen_mol1237   1.0             -7.451    0.000    0.000
4188   gen_mol1422   1.0             -7.442    0.000    0.000
15708   gen_mol980   1.0             -7.340    0.000    0.000
15288   gen_mol938   1.0             -7.336    0.000    0.000
4994   gen_mol1503   1.0             -7.331    0.000    0.000
502    gen_mol1051   1.0             -7.319    0.000    0.000
7379   gen_mol1743   1.0             -7.317    0.000    0.000
4125   gen_mol1415   1.0             -7.313    0.000    0.000
4995   gen_mol1503   2.0             -7.286    1.549    6.936

In [9]:
docking_df.to_csv(path + 'all_results_preproc.csv', index=False)

In [10]:
docking_df.groupby('name').agg({'affinity_kcal_mol': 'median'}).sort_values(['affinity_kcal_mol'])

             affinity_kcal_mol
name
gen_mol1237             -7.081
gen_mol1422             -6.998
gen_mol1631             -6.873
gen_mol1659             -6.859
gen_mol1694             -6.829
...                        ...
gen_mol1735             -4.304
gen_mol1572             -4.270
gen_mol1563             -4.246
gen_mol1577             -4.233
gen_mol1573             -4.209

[1774 rows x 1 columns]